version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version

  pre_build:
    commands:
      - echo Checking AWS CLI and CodeArtifact availability...
      - aws --version
      - aws codeartifact help
      - echo Logging in to AWS CodeArtifact...
      - aws codeartifact login --tool maven --repository nextwork-devops-cicd --domain nextwork --domain-owner 165581927178 --region eu-west-2

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
