version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - export PATH=$PWD/aws/dist:$PATH
      - aws --version

  pre_build:
    commands:
      - echo Getting CodeArtifact token...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 165581927178 --region eu-west-2 --query authorizationToken --output text)
      - echo Token acquired

  build:
    commands:
      - echo Building Maven project with CodeArtifact auth token...
      - mvn -s settings.xml -Daws.codeartifact.authToken=$CODEARTIFACT_AUTH_TOKEN package

  post_build:
    commands:
      - echo Build complete on `date`

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
