version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Initializing environment
      - aws codeartifact login --tool maven --repository nextwork-devops-cicd --domain nextwork --domain-owner 165581927178 --region eu-west-2

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no

